CREATE DATABASE login_db;

CREATE TABLE users (
id_user INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(20) NOT NULL,
lastname VARCHAR(20) NOT NULL,
age INT(3) NOT NULL,
mail VARCHAR(20) NOT NULL,
clave VARCHAR(20) NOT NULL
);

SELECT * FROM users;
